name: unused_l10n
description: A sample command-line application to remove unused l10n terms.
version: 1.0.0

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  glob: ^2.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
